victor_ad:
    resource: "@VictorAdBundle/Resources/config/routing.yml"
    prefix:   /

login:
    path: /login
    defaults:
        _controller: VictorUserBundle:Security:login

login_check:
    path: /login_check

logout:
    path: /logout
