victor_ad_sell:
    path: /sell
    defaults: { _controller: VictorAdBundle:Advert:sell}

victor_ad_sellview:
    path: /sell/{phone}
    defaults: { _controller: VictorAdBundle:Advert:sellview}

victor_ad_sellviewphone:
    path: /sell/{phone}/{id}
    defaults: { _controller: VictorAdBundle:Advert:sellviewphone}

victor_ad_buy:
    path: /buy
    defaults: { _controller: VictorAdBundle:Advert:buy}

victor_ad_buyview:
    path: /buy/{phone}
    defaults: { _controller: VictorAdBundle:Advert:buyview}

victor_ad_buyviewphone:
    path: /buy/{phone}/{id}
    defaults: { _controller: VictorAdBundle:Advert:buyviewphone}

victor_ad_view:
    path: /advert/{id}
    defaults: { _controller: VictorAdBundle:Advert:view}
    requirements:
        departement:    \d{2}

victor_ad_add:
    path: /add
    defaults: { _controller: VictorAdBundle:Advert:add}

victor_ad_delete:
    path: /delete/{id}
    defaults: { _controller: VictorAdBundle:Advert:delete}

victor_ad_admin:
    path: /admin
    defaults: { _controller: VictorAdBundle:Admin:admin}

victor_ad_deleteuser:
    path: /admin/delete/{user}
    defaults: { _controller: VictorAdBundle:Admin:delete}

victor_ad_deactivateuser:
    path: /admin/deactivate/{user}
    defaults: { _controller: VictorAdBundle:Admin:deactivate}

victor_ad_promoteuser:
    path: /admin/promote/{user}
    defaults: { _controller: VictorAdBundle:Admin:promote}

victor_ad_demoteuser:
    path: /admin/demote/{user}
    defaults: { _controller: VictorAdBundle:Admin:demote}

victor_ad_account:
    path: /account
    defaults: { _controller: VictorAdBundle:Account:account}

victor_ad_data:
    path: /account/data
    defaults: { _controller: VictorAdBundle:Account:data}

victor_ad_editprofile:
    path: /account/data/edit
    defaults: { _controller: VictorAdBundle:Account:editprofile}
