victor_ad_sell:
    path: /sell
    defaults: { _controller: VictorAdBundle:Advert:sell}

victor_ad_sellview:
    path: /sell/{phone}
    defaults: { _controller: VictorAdBundle:Advert:sellview}

victor_ad_sellviewphone:
    path: /sell/{phone}/{id}
    defaults: { _controller: VictorAdBundle:Advert:sellviewphone}

victor_ad_selloffer:
    path: /sell/{phone}/{id}/offer
    defaults: { _controller: VictorAdBundle:Advert:selloffer}

victor_ad_buy:
    path: /buy
    defaults: { _controller: VictorAdBundle:Advert:buy}

victor_ad_buyview:
    path: /buy/{phone}
    defaults: { _controller: VictorAdBundle:Advert:buyview}

victor_ad_buyviewphone:
    path: /buy/{phone}/{id}
    defaults: { _controller: VictorAdBundle:Advert:buyviewphone}

victor_ad_summarybuy:
    path: /buy/{phone}/{id}/summary/{offerid}
    defaults: { _controller: VictorAdBundle:Advert:summarybuy}

victor_ad_delete:
    path: /delete/{id}
    defaults: { _controller: VictorAdBundle:Advert:delete}

victor_ad_admin:
    path: /admin
    defaults: { _controller: VictorAdBundle:Admin:admin}

victor_ad_deleteuser:
    path: /admin/delete/{user}
    defaults: { _controller: VictorAdBundle:Admin:delete}

victor_ad_deactivateuser:
    path: /admin/deactivate/{user}
    defaults: { _controller: VictorAdBundle:Admin:deactivate}

victor_ad_promoteuser:
    path: /admin/promote/{user}
    defaults: { _controller: VictorAdBundle:Admin:promote}

victor_ad_demoteuser:
    path: /admin/demote/{user}
    defaults: { _controller: VictorAdBundle:Admin:demote}

victor_ad_addphone:
    path: /admin/addphone
    defaults: { _controller: VictorAdBundle:Admin:addphone}

victor_ad_order:
    path: /admin/order
    defaults: { _controller: VictorAdBundle:Admin:order}

victor_ad_order2:
    path: /admin/order2
    defaults: { _controller: VictorAdBundle:Admin:order2}

victor_ad_order3:
    path: /admin/order3
    defaults: { _controller: VictorAdBundle:Admin:order3}

victor_ad_order4:
    path: /admin/order4
    defaults: { _controller: VictorAdBundle:Admin:order4}

victor_ad_cancel:
    path: /admin/cancel/{id}
    defaults: { _controller: VictorAdBundle:Admin:cancel}

victor_ad_account:
    path: /account
    defaults: { _controller: VictorAdBundle:Account:account}

victor_ad_deleteconfirm:
    path: /account/delete
    defaults: { _controller: VictorAdBundle:Account:delete}

victor_ad_deletehimself:
    path: /account/delete/himself
    defaults: { _controller: VictorAdBundle:Account:deletehimself}

victor_ad_purchases:
    path: /account/purchases
    defaults: { _controller: VictorAdBundle:Account:purchases}

victor_ad_sales:
    path: /account/sales
    defaults: { _controller: VictorAdBundle:Account:sales}

victor_ad_currentoffer:
    path: /account/currentoffer
    defaults: { _controller: VictorAdBundle:Account:currentoffer}

victor_ad_ordertracking:
    path: /account/ordertracking/{id}
    defaults: { _controller: VictorAdBundle:Account:ordertracking}

victor_ad_subscription:
    path: /account/unsubscribe
    defaults: { _controller: VictorAdBundle:Account:subscription}

victor_ad_paiement:
    path: /paiement/{offerid}
    defaults: { _controller: VictorAdBundle:Advert:paiement}

victor_ad_ordercheckout:
    path: /checkout/{offerid}
    defaults: { _controller: VictorAdBundle:Advert:checkout}

victor_ad_increase:
    path: /admin/order/{id}
    defaults: { _controller: VictorAdBundle:Admin:increase}

victor_ad_decrease:
    path: /admin/order/decrease/{id}
    defaults: { _controller: VictorAdBundle:Admin:decrease}