services:
    victor_ad.ordertracking:
        class: Victor\AdBundle\Tracking\OrderTracking
        arguments:
            - "@security.token_storage"

#    victor_ad.example:
#        class: Victor\AdBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    victor_ad.mailer:
        class: Victor\AdBundle\Mailer\Mailer
        arguments:
            - "@mailer"
            - "@templating"

    victor_ad.stepincreasemail:
        class: Victor\AdBundle\Tracking\IncreaseStepMail
        arguments:
            - "@victor_ad.mailer"


